apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml

namespace: goserver

images:
- name: goserver
  newName: dominickbrasileiro/k8s-gitops-prototype
  newTag: invalid-tag
