apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: goserver

images:
- name: goserver
  newName: dominickbrasileiro/k8s-gitops-prototype
  newTag: f6dea76befa993053b464d18c85dcbd67724aa2f
