apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: dominickbrasileiro/k8s-gitops-prototype
  newTag: bae8539e8e8b144c2f46961f4c9ee45cc1437698
